#!/bin/sh
# Xcode Cloud looks for ci_scripts beside the Xcode project, which is why this
# lives in ios/App rather than the repository root.
#
# It clones the repo and then builds ios/App/App.xcodeproj. capacitor.config.json,
# config.xml and the web bundle under App/public are all generated by `cap sync`
# and gitignored, so without this step the archive has nothing to wrap.
#
# This also exists because App Store submissions cannot be built on a beta
# macOS (ITMS-90111), and the machine this app is developed on runs one.
set -eu

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Xcode Cloud stamps its own run counter as the uploaded build number, and it
# ignores anything the project or a pre-build script sets. This app already has
# builds up to 18 in App Store Connect from local archives, so any run at or
# below that is rejected on upload for going backwards. Fail in forty seconds
# instead of spending a full archive to learn it again.
HIGHEST_UPLOADED=18
if [ "${CI_BUILD_NUMBER:-0}" -le "$HIGHEST_UPLOADED" ]; then
  echo "run $CI_BUILD_NUMBER uploads as build $CI_BUILD_NUMBER, which is not above the $HIGHEST_UPLOADED already in App Store Connect"
  exit 1
fi

if ! command -v node > /dev/null 2>&1; then
  echo "installing node"
  brew install node@20
  brew link --overwrite --force node@20
fi

echo "node $(node -v), npm $(npm -v)"

npm ci --no-audit --no-fund

CI=true npx react-scripts test --watchAll=false
CI=true npm run build

npx cap sync ios
node scripts/enforce-ios-deployment-target.mjs

# Prove the archive will carry this build, not an empty shell.
test -f ios/App/App/public/index.html
grep -q 'static/js/main\.' ios/App/App/public/index.html
echo "web bundle in place: $(grep -o 'main\.[0-9a-f]*\.js' ios/App/App/public/index.html | head -1)"
